package com.myspace.demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class sample implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public sample() {
    }




}